server:
  port: 9091

logging:
   level:
     web: debug
     com.data.faker.app.consumer.DataFlowConsumer: debug
     com.data.faker.app.consumer.RabbitMqConsumer: debug
#spring:
#  data:
#    mongodb:
#      host: localhost
#      port: 27017
#      database: datafakerdb
#      repositories:
#        type: REACTIVE


mongock:
  migration-scan-package:
    - com.data.faker.app.changelogs
  transaction-strategy: CHANGE_UNIT
  lock-acquired-for-millis: 900000

spring:
  activemq:
    user: admin
    password: admin
    broker-url: tcp://localhost:61616
    pool:
      enabled: true
      max-connections: 50
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

rabbitmq:
  queue:
    name: dataflow_queue
  exchange:
    name: dataflow_exchange
  routing:
    key: dataflow_routing_key